apiVersion: v1
kind: Secret
metadata:
  name: app
type: Opaque
data:
  JWT_SECRET: TTlERkQ5RE4zS0RPN085REs3OEtEVTc4VU03OERETDc4TERMOTlKOFNMQTk5TEZKOUtLTDlGTDJKREsyS0s4Rkw0TExKN0tEREhTTEtTSkpT
  JWT_PREFIX: QmVhcmVyIA==