apiVersion: v1
kind: Secret
metadata:
  name: app
type: Opaque
data:
  JWT_SECRET: TTlERkQ5RE4zS0RPN085REs3OEtEVTc4VU03OERETDc4TERMOTlKOFNMQTk5TEZKOUtLTDlGTDJKREsyS0s4Rkw0TExKN0tEREhTTEtTSkpT
  JWT_PREFIX: QmVhcmVyIA==
  ORDER_PAYMENT_SECRET_KEY: b3JkZXItcGF5bWVudC1zZWNyZXQta2V5
  PAYMENT_BANK_SECRET_KEY: cGF5bWVudC1iYW5rLXNlY3JldC1rZXk=
  PAYMENT_CC_SECRET_KEY: cGF5bWVudC1jYy1zZWNyZXQta2V5
  PAYMENT_PAYPAL_SECRET_KEY: cGF5bWVudC1wYXlwYWwtc2VjcmV0LWtleQ==
  ORDER_NOTIFICATION_SECRET_KEY: b3JkZXItbm90aWZpY2F0aW9uLXNlY3JldC1rZXk=