apiVersion: v1
kind: ConfigMap
metadata:
  name: app
data:
  APP_PROFILE: prod
  DATABASE_URL: database-service
  DATABASE_PORT: "3306"
  USER_DATABASE_NAME: user-db
  PRODUCT_DATABASE_NAME: product-db