apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: prabeensoti/user-service
          ports:
            - containerPort: 8080
          env:
            - name: APP_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: APP_PROFILE
            - name: MYSQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysqldb
                  key: DATABASE_URL
            - name: MYSQL_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: mysqldb
                  key: DATABASE_PORT
            - name: MYSQL_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: USER_DATABASE_NAME
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysqldb
                  key: DATABASE_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqldb
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app
                  key: JWT_SECRET
            - name: JWT_PREFIX
              valueFrom:
                secretKeyRef:
                  name: app
                  key: JWT_PREFIX
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: user-service